[package]
name = "sp1-helios-script"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "genesis"
path = "bin/genesis.rs"

[[bin]]
name = "operator" 
path = "bin/operator.rs"

[[bin]]
name = "test"
path = "bin/test.rs"

[dependencies]
sp1-helios-primitives = { path = "../primitives" }
alloy = { workspace = true, features = ["full"] }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-trie = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-sol-macro = { workspace = true }
anyhow = { workspace = true }
arrayvec = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
helios = { workspace = true }
helios-consensus-core = { workspace = true }
helios-ethereum = { workspace = true }
log = { workspace = true }
nybbles = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
smallvec = { workspace = true }
sp1-sdk = { workspace = true }
ssz-rs = { workspace = true }
tokio = { workspace = true, features = ["full", "macros"] }
tree_hash = { workspace = true }
reqwest = { workspace = true }
[build-dependencies]
sp1-build = { workspace = true }